# pull, npm install, npm run build, gcloud app deploy app.yaml

env: standard
runtime: nodejs10
service: default

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|png|jpg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png|jpg)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always
